<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG1_Conveyer_Operation" Id="{45b7ed08-ad47-4fa3-b041-11199023376c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG1_Conveyer_Operation
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG1_Conveyer_Operation">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>